# Generated by Django 3.0.3 on 2020-02-29 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200229_1709'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
